---
- hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: update apt cache
      apt: update_cache=yes cache_valid_time=86400

- import_playbook: initial.yml
- import_playbook: master.yml
- import_playbook: workers.yml